
create_bd_port -dir I ref_clk_c
create_bd_port -dir I ref_clk_d

create_bd_port -dir I core_clk_c
create_bd_port -dir I core_clk_d

create_bd_port -dir I -from 31 -to 0 fmcomms8_gpio0_i
create_bd_port -dir O -from 31 -to 0 fmcomms8_gpio0_o
create_bd_port -dir O -from 31 -to 0 fmcomms8_gpio0_t
create_bd_port -dir I -from 31 -to 0 fmcomms8_gpio1_i
create_bd_port -dir O -from 31 -to 0 fmcomms8_gpio1_o
create_bd_port -dir O -from 31 -to 0 fmcomms8_gpio1_t

ad_ip_instance axi_gpio axi_fmcomms8_gpio
ad_ip_parameter axi_fmcomms8_gpio CONFIG.C_IS_DUAL 1
ad_ip_parameter axi_fmcomms8_gpio CONFIG.C_GPIO_WIDTH 32
ad_ip_parameter axi_fmcomms8_gpio CONFIG.C_GPIO2_WIDTH 32
ad_ip_parameter axi_fmcomms8_gpio CONFIG.C_INTERRUPT_PRESENT 1

ad_connect  fmcomms8_gpio0_i axi_fmcomms8_gpio/gpio_io_i
ad_connect  fmcomms8_gpio0_o axi_fmcomms8_gpio/gpio_io_o
ad_connect  fmcomms8_gpio0_t axi_fmcomms8_gpio/gpio_io_t
ad_connect  fmcomms8_gpio1_i axi_fmcomms8_gpio/gpio2_io_i
ad_connect  fmcomms8_gpio1_o axi_fmcomms8_gpio/gpio2_io_o
ad_connect  fmcomms8_gpio1_t axi_fmcomms8_gpio/gpio2_io_t

ad_xcvrpll  ref_clk_c util_adrv9009_som_xcvr/qpll_ref_clk_8
ad_xcvrpll  ref_clk_d util_adrv9009_som_xcvr/cpll_ref_clk_8
ad_xcvrpll  ref_clk_d util_adrv9009_som_xcvr/cpll_ref_clk_9
ad_xcvrpll  ref_clk_c util_adrv9009_som_xcvr/cpll_ref_clk_10
ad_xcvrpll  ref_clk_c util_adrv9009_som_xcvr/cpll_ref_clk_11
ad_xcvrpll  ref_clk_c util_adrv9009_som_xcvr/qpll_ref_clk_12
ad_xcvrpll  ref_clk_d util_adrv9009_som_xcvr/cpll_ref_clk_12
ad_xcvrpll  ref_clk_d util_adrv9009_som_xcvr/cpll_ref_clk_13
ad_xcvrpll  ref_clk_c util_adrv9009_som_xcvr/cpll_ref_clk_14
ad_xcvrpll  ref_clk_c util_adrv9009_som_xcvr/cpll_ref_clk_15

ad_xcvrpll  axi_adrv9009_som_tx_xcvr/up_pll_rst util_adrv9009_som_xcvr/up_qpll_rst_8
ad_xcvrpll  axi_adrv9009_som_rx_xcvr/up_pll_rst util_adrv9009_som_xcvr/up_cpll_rst_8
ad_xcvrpll  axi_adrv9009_som_rx_xcvr/up_pll_rst util_adrv9009_som_xcvr/up_cpll_rst_9
ad_xcvrpll  axi_adrv9009_som_obs_xcvr/up_pll_rst util_adrv9009_som_xcvr/up_cpll_rst_10
ad_xcvrpll  axi_adrv9009_som_obs_xcvr/up_pll_rst util_adrv9009_som_xcvr/up_cpll_rst_11
ad_xcvrpll  axi_adrv9009_som_tx_xcvr/up_pll_rst util_adrv9009_som_xcvr/up_qpll_rst_12
ad_xcvrpll  axi_adrv9009_som_rx_xcvr/up_pll_rst util_adrv9009_som_xcvr/up_cpll_rst_12
ad_xcvrpll  axi_adrv9009_som_rx_xcvr/up_pll_rst util_adrv9009_som_xcvr/up_cpll_rst_13
ad_xcvrpll  axi_adrv9009_som_obs_xcvr/up_pll_rst util_adrv9009_som_xcvr/up_cpll_rst_14
ad_xcvrpll  axi_adrv9009_som_obs_xcvr/up_pll_rst util_adrv9009_som_xcvr/up_cpll_rst_15

ad_connect tx_adrv9009_som_tpl_core/dac_data_8  util_som_tx_upack/fifo_rd_data_0
ad_connect tx_adrv9009_som_tpl_core/dac_data_9  util_som_tx_upack/fifo_rd_data_1
ad_connect tx_adrv9009_som_tpl_core/dac_data_10 util_som_tx_upack/fifo_rd_data_2
ad_connect tx_adrv9009_som_tpl_core/dac_data_11 util_som_tx_upack/fifo_rd_data_3
ad_connect tx_adrv9009_som_tpl_core/dac_data_12 util_som_tx_upack/fifo_rd_data_4
ad_connect tx_adrv9009_som_tpl_core/dac_data_13 util_som_tx_upack/fifo_rd_data_5
ad_connect tx_adrv9009_som_tpl_core/dac_data_14 util_som_tx_upack/fifo_rd_data_6
ad_connect tx_adrv9009_som_tpl_core/dac_data_15 util_som_tx_upack/fifo_rd_data_7

delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_2]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_3]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_6]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_7]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_8]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_9]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_12]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_13]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_10]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_11]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_14]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_15]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_4]
delete_bd_objs [get_bd_intf_nets util_adrv9009_som_xcvr_rx_5]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_es_0]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_ch_0]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_es_1]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_ch_1]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_es_2]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_ch_2]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_es_3]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_ch_3]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_es_4]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_ch_4]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_es_5]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_ch_5]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_es_6]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_ch_6]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_es_7]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_obs_xcvr_up_ch_7]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_es_2]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_ch_2]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_es_3]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_ch_3]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_es_4]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_ch_4]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_es_5]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_ch_5]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_es_6]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_ch_6]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_es_7]
delete_bd_objs [get_bd_intf_nets axi_adrv9009_som_rx_xcvr_up_ch_7]

ad_connect util_adrv9009_som_xcvr/rx_4 axi_adrv9009_som_rx_jesd/rx_phy2
ad_connect util_adrv9009_som_xcvr/rx_5 axi_adrv9009_som_rx_jesd/rx_phy3
ad_connect util_adrv9009_som_xcvr/rx_8 axi_adrv9009_som_rx_jesd/rx_phy4
ad_connect util_adrv9009_som_xcvr/rx_9 axi_adrv9009_som_rx_jesd/rx_phy5
ad_connect util_adrv9009_som_xcvr/rx_12 axi_adrv9009_som_rx_jesd/rx_phy6
ad_connect util_adrv9009_som_xcvr/rx_13 axi_adrv9009_som_rx_jesd/rx_phy7

ad_connect util_adrv9009_som_xcvr/rx_2 axi_adrv9009_som_obs_jesd/rx_phy0
ad_connect util_adrv9009_som_xcvr/rx_3 axi_adrv9009_som_obs_jesd/rx_phy1
ad_connect util_adrv9009_som_xcvr/rx_6 axi_adrv9009_som_obs_jesd/rx_phy2
ad_connect util_adrv9009_som_xcvr/rx_7 axi_adrv9009_som_obs_jesd/rx_phy3
ad_connect util_adrv9009_som_xcvr/rx_10 axi_adrv9009_som_obs_jesd/rx_phy4
ad_connect util_adrv9009_som_xcvr/rx_11 axi_adrv9009_som_obs_jesd/rx_phy5
ad_connect util_adrv9009_som_xcvr/rx_14 axi_adrv9009_som_obs_jesd/rx_phy6
ad_connect util_adrv9009_som_xcvr/rx_15 axi_adrv9009_som_obs_jesd/rx_phy7

ad_connect axi_adrv9009_som_rx_xcvr/up_es_2 util_adrv9009_som_xcvr/up_es_4
ad_connect axi_adrv9009_som_rx_xcvr/up_ch_2 util_adrv9009_som_xcvr/up_rx_4
ad_connect axi_adrv9009_som_rx_xcvr/up_es_3 util_adrv9009_som_xcvr/up_es_5
ad_connect axi_adrv9009_som_rx_xcvr/up_ch_3 util_adrv9009_som_xcvr/up_rx_5
ad_connect axi_adrv9009_som_rx_xcvr/up_es_4 util_adrv9009_som_xcvr/up_es_8
ad_connect axi_adrv9009_som_rx_xcvr/up_ch_4 util_adrv9009_som_xcvr/up_rx_8
ad_connect axi_adrv9009_som_rx_xcvr/up_es_5 util_adrv9009_som_xcvr/up_es_9
ad_connect axi_adrv9009_som_rx_xcvr/up_ch_5 util_adrv9009_som_xcvr/up_rx_9
ad_connect axi_adrv9009_som_rx_xcvr/up_es_6 util_adrv9009_som_xcvr/up_es_12
ad_connect axi_adrv9009_som_rx_xcvr/up_ch_6 util_adrv9009_som_xcvr/up_rx_12
ad_connect axi_adrv9009_som_rx_xcvr/up_es_7 util_adrv9009_som_xcvr/up_es_13
ad_connect axi_adrv9009_som_rx_xcvr/up_ch_7 util_adrv9009_som_xcvr/up_rx_13

ad_connect axi_adrv9009_som_obs_xcvr/up_es_0 util_adrv9009_som_xcvr/up_es_2
ad_connect axi_adrv9009_som_obs_xcvr/up_ch_0 util_adrv9009_som_xcvr/up_rx_2
ad_connect axi_adrv9009_som_obs_xcvr/up_es_1 util_adrv9009_som_xcvr/up_es_3
ad_connect axi_adrv9009_som_obs_xcvr/up_ch_1 util_adrv9009_som_xcvr/up_rx_3
ad_connect axi_adrv9009_som_obs_xcvr/up_es_2 util_adrv9009_som_xcvr/up_es_6
ad_connect axi_adrv9009_som_obs_xcvr/up_ch_2 util_adrv9009_som_xcvr/up_rx_6
ad_connect axi_adrv9009_som_obs_xcvr/up_es_3 util_adrv9009_som_xcvr/up_es_7
ad_connect axi_adrv9009_som_obs_xcvr/up_ch_3 util_adrv9009_som_xcvr/up_rx_7
ad_connect axi_adrv9009_som_obs_xcvr/up_es_4 util_adrv9009_som_xcvr/up_es_10
ad_connect axi_adrv9009_som_obs_xcvr/up_ch_4 util_adrv9009_som_xcvr/up_rx_10
ad_connect axi_adrv9009_som_obs_xcvr/up_es_5 util_adrv9009_som_xcvr/up_es_11
ad_connect axi_adrv9009_som_obs_xcvr/up_ch_5 util_adrv9009_som_xcvr/up_rx_11
ad_connect axi_adrv9009_som_obs_xcvr/up_es_6 util_adrv9009_som_xcvr/up_es_14
ad_connect axi_adrv9009_som_obs_xcvr/up_ch_6 util_adrv9009_som_xcvr/up_rx_14
ad_connect axi_adrv9009_som_obs_xcvr/up_es_7 util_adrv9009_som_xcvr/up_es_15
ad_connect axi_adrv9009_som_obs_xcvr/up_ch_7 util_adrv9009_som_xcvr/up_rx_15

disconnect_bd_net /core_clk_b_1 [get_bd_pins util_adrv9009_som_xcvr/rx_clk_2]
disconnect_bd_net /core_clk_b_1 [get_bd_pins util_adrv9009_som_xcvr/rx_clk_3]
disconnect_bd_net /core_clk_b_1 [get_bd_pins util_adrv9009_som_xcvr/rx_clk_6]
disconnect_bd_net /core_clk_b_1 [get_bd_pins util_adrv9009_som_xcvr/rx_clk_7]
disconnect_bd_net /core_clk_a_1 [get_bd_pins util_adrv9009_som_xcvr/rx_clk_8]
disconnect_bd_net /core_clk_a_1 [get_bd_pins util_adrv9009_som_xcvr/rx_clk_9]
disconnect_bd_net /core_clk_a_1 [get_bd_pins util_adrv9009_som_xcvr/rx_clk_12]
disconnect_bd_net /core_clk_a_1 [get_bd_pins util_adrv9009_som_xcvr/rx_clk_13]

connect_bd_net [get_bd_ports core_clk_a] [get_bd_pins util_adrv9009_som_xcvr/rx_clk_2]
connect_bd_net [get_bd_ports core_clk_a] [get_bd_pins util_adrv9009_som_xcvr/rx_clk_3]
connect_bd_net [get_bd_ports core_clk_a] [get_bd_pins util_adrv9009_som_xcvr/rx_clk_6]
connect_bd_net [get_bd_ports core_clk_a] [get_bd_pins util_adrv9009_som_xcvr/rx_clk_7]
connect_bd_net [get_bd_ports core_clk_b] [get_bd_pins util_adrv9009_som_xcvr/rx_clk_8]
connect_bd_net [get_bd_ports core_clk_b] [get_bd_pins util_adrv9009_som_xcvr/rx_clk_9]
connect_bd_net [get_bd_ports core_clk_b] [get_bd_pins util_adrv9009_som_xcvr/rx_clk_12]
connect_bd_net [get_bd_ports core_clk_b] [get_bd_pins util_adrv9009_som_xcvr/rx_clk_13]

ad_cpu_interconnect 0x46000000 axi_fmcomms8_gpio

# interconnect (mem/dac)

ad_cpu_interrupt ps-4 mb-4 axi_fmcomms8_gpio/ip2intc_irpt
